#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."


# Make a virtual environment
python3 -m venv ~/opt/venv

# Activate the virtual environment
. ~/opt/venv/bin/activate

# Install the packages via the active venv pip
pip install -r requirements.txt
python3 -m pip install --requirement requirements.txt
