# Describes the format for available Number entity services
turn_on:
  name: Enable PID controller
  description: Enable the PID controller.
  target:
    entity:
      integration: pid_controller

turn_off:
  name: Disable PID controller
  description: Disable the PID controller.
  target:
    entity:
      integration: pid_controller
